[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
macroquad = { version = "0.4.6", features = ["audio"] }
src = "0.0.6"
